export const IdVideos = [
    {
        id: 1,
        title: "Interstellar (Trailer)",
        videoSrc: "https://res.cloudinary.com/da6ne7pa0/video/upload/v1726345084/Interstellar_-_Trailer_-_Official_Warner_Bros._UK_hntie9.mp4",
        videoThumbnail: "/interstellar_image.jpeg",
        author: "Christopher Nolan",
        authorThumbnail: "/interstellar_image.jpeg",
        views: "1.2M",
        timeStamp: "1 Week ago",
    },
    {
        id: 2,
        title: "The Godfather (Trailer)",
        videoSrc: "https://res.cloudinary.com/da6ne7pa0/video/upload/v1726346034/The_Godfather_1972___Official_Hindi_Trailer___HollyTrailer_Network_yjniet.mp4",
        videoThumbnail: "/godfather_image.jpg",
        author: "Francis Ford Coppola",
        authorThumbnail: "/godfather_image.jpg",
        views: "850K",
        timeStamp: "3 Weeks ago",
    },
    {
        id: 3,
        title: "La La Land (Trailer)",
        videoSrc: "https://res.cloudinary.com/da6ne7pa0/video/upload/v1726345940/La_La_Land_2016_Movie_Official_Trailer_Dreamers_zh2oxy.mp4",
        videoThumbnail: "/lalaland_image.jpeg",
        author: "Damien Chazelle",
        authorThumbnail: "/lalaland_image.jpeg",
        views: "920K",
        timeStamp: "2 Months ago",
    },
    {
        id: 4,
        title: "Gone Girl (Trailer)",
        videoSrc: "https://res.cloudinary.com/da6ne7pa0/video/upload/v1726345652/Gone_Girl___Official_Trailer_HD___20th_Century_FOX_idtqz3.mp4",
        videoThumbnail: "/gonegirl_image.jpg",
        author: "David Fincher",
        authorThumbnail: "/gonegirl_image.jpg",
        views: "1.1M",
        timeStamp: "4 Days ago",
    },
    {
        id: 5,
        title: "El Camino (Trailer)",
        videoSrc: "https://res.cloudinary.com/da6ne7pa0/video/upload/v1726345589/El_Camino__A_Breaking_Bad_Movie___Official_Trailer___Netflix_emdkvh.mp4",
        videoThumbnail: "/elcamino_image.jpg",
        author: "Vince Gilligan",
        authorThumbnail: "/elcamino_image.jpg",
        views: "760K",
        timeStamp: "2 Weeks ago",
    },
    {
        id: 6,
        title: "Shutter Island (Trailer)",
        videoSrc: "https://res.cloudinary.com/da6ne7pa0/video/upload/v1726346120/Shutter_Island_-_Official_Trailer_HD_jzrebl.mp4",
        videoThumbnail: "/shutterisland_image.jpg",
        author: "Martin Scorsese",
        authorThumbnail: "/shutterisland_image.jpg",
        views: "1.3M",
        timeStamp: "5 Months ago",
    },
    {
        id: 7,
        title: "Fight Club (Trailer)",
        videoSrc: "https://res.cloudinary.com/da6ne7pa0/video/upload/v1726346233/Fight_Club_1999_Trailer_1___Movieclips_Classic_Trailers_n4tge2.mp4",
        videoThumbnail: "/fightclub_image.jpg",
        author: "David Fincher",
        authorThumbnail: "/fightclub_image.jpg",
        views: "900K",
        timeStamp: "1 Month ago",
    },
    {
        id: 8,
        title: "Infinity War (Trailer)",
        videoSrc: "https://res.cloudinary.com/da6ne7pa0/video/upload/v1726346297/Marvel_Studios_Avengers__Infinity_War_Official_Trailer_wbu1df.mp4",
        videoThumbnail: "/infinitywar_image.jpg",
        author: "Anthony and Joe Russo",
        authorThumbnail: "/infinitywar_image.jpg",
        views: "2.5M",
        timeStamp: "6 Weeks ago",
    },
    {
        id: 9,
        title: "Endgame (Trailer)",
        videoSrc: "https://res.cloudinary.com/da6ne7pa0/video/upload/v1726346362/Marvel_Studios_Avengers__Endgame_-_Official_Trailer_rjzwfs.mp4",
        videoThumbnail: "/endgame_image.jpg",
        author: "Anthony and Joe Russo",
        authorThumbnail: "/endgame_image.jpg",
        views: "3.2M",
        timeStamp: "2 Months ago",
    },
    {
        id: 10,
        title: "Oppenheimer (Trailer)",
        videoSrc: "https://res.cloudinary.com/da6ne7pa0/video/upload/v1726346421/Oppenheimer___New_Trailer_roswfc.mp4",
        videoThumbnail: "/oppenheimer_image.jpg",
        author: "Christopher Nolan",
        authorThumbnail: "/oppenheimer_image.jpg",
        views: "1.8M",
        timeStamp: "3 Weeks ago",
    },
    {
        id: 11,
        title: "Seven (Trailer)",
        videoSrc: "https://res.cloudinary.com/da6ne7pa0/video/upload/v1726345404/Se7en_1995_Official_Trailer_-_Brad_Pitt_Morgan_Freeman_Movie_HD_ihhhq6.mp4",
        videoThumbnail: "/seven_image.jpg",
        author: "David Fincher",
        authorThumbnail: "/seven_image.jpg",
        views: "1.0M",
        timeStamp: "8 Weeks ago",
    },
    {
        id: 12,
        title: "Whiplash (Trailer)",
        videoSrc: "https://res.cloudinary.com/da6ne7pa0/video/upload/v1726345352/Whiplash_TRAILER_1_2014_-_J.K._Simmons_Miles_Teller_Movie_HD_a3ifmg.mp4",
        videoThumbnail: "/whiplash_image.jpg",
        author: "Damien Chazelle",
        authorThumbnail: "/whiplash_image.jpg",
        views: "950K",
        timeStamp: "1 Month ago",
    },
];
